a = input(" Your first number   :")
b = input(" Your second number  :")
c = input(" Your third number   :")
d = input(" Your fourth number  :")
e = input(" Your fifth number   :")

print("Float of %s is  "%a,float(a))
print("Complex of %s is"%a,complex(a))
print("Float of %s is "%b,float(b))
print("Complex of %s is"%b,complex(b))
print("Float of %s is "%c,float(c))
print("Complex of %s is"%c,complex(c))
print("Float of %s is "%d,float(d))
print("Complex of %s is"%d,complex(d))
print("Float of %s is "%e,float(e))
print("Complex of %s is"%e,complex(e))