print("โปรแกรมหยิบสินค้าใส่ตะกร้า")
basket=[]
Shop1 = input("หยิบสินค้าชิ้นที่หนึ่ง :")
basket.append(Shop1)
Shop2 = input("หยิบสินค้าชิ้นที่สอง :")
basket.append(Shop2)
Shop3 = input("หยิบสินค้าชิ้นที่สาม :")
basket.append(Shop3)
Shop4 = input("หยิบสินค้าชิ้นที่สี่ :")
basket.append(Shop4)
Shop5 = input("หยิบสินค้าชิ้นที่ห้า :")
basket.append(Shop5)
print("สินค้าในตะกร้า โปรดจ่ายตังค์ \n",basket)